name: languagetool_textformfield
description: This is a fork of languagetool_textfield widget. All major work was done by Solid Software Team, and LanguageTool Team. I merely need to adapt this work to my use case but do not claim authorship.
version: 0.0.1
homepage: https://github.com/fedorSulitskiy/languagetool_textformfield


environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  async: ^2.11.0
  collection: ^1.17.1
  flutter:
    sdk: flutter
  http: ^1.0.0
  throttling: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  solid_lints: ^0.0.14

flutter:
  uses-material-design: true
  assets:
    - images/symbol_boxed_white.png
